package services

import (
	"context"
	"fmt"

	"cpd-nexus/internal/core/domain"
	"cpd-nexus/internal/core/ports"
	"cpd-nexus/internal/pkg/apperrors"
	"cpd-nexus/internal/pkg/timeutil"
	"cpd-nexus/internal/pkg/validation"
)

type WorkerService struct {
	repo             ports.WorkerRepository
	analyticsService ports.AnalyticsService
}

func NewWorkerService(repo ports.WorkerRepository, analytics ports.AnalyticsService) ports.WorkerService {
	return &WorkerService{repo: repo, analyticsService: analytics}
}

func (s *WorkerService) GetWorker(ctx context.Context, userID, id string) (*domain.Worker, error) {
	if userID == "" && !ports.IsVendor(ctx) {
		return nil, apperrors.NewPermissionDenied("user_id scope required")
	}
	// Inject isVendor into context so repo can check it without importing middleware
	ctx = context.WithValue(ctx, ports.IsVendorKey, ports.IsVendor(ctx))
	worker, err := s.repo.Get(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	return worker, nil
}

func (s *WorkerService) ListWorkers(ctx context.Context, userID, siteID string) ([]domain.Worker, error) {
	// Inject isVendor into context so repo can check it without importing middleware
	ctx = context.WithValue(ctx, ports.IsVendorKey, ports.IsVendor(ctx))
	return s.repo.List(ctx, userID, siteID)
}

func (s *WorkerService) CreateWorker(ctx context.Context, w *domain.Worker) error {
	if err := s.validateWorker(w); err != nil {
		return err
	}
	// ID is generated by the repository via idgen.GenerateNextID — do not set it here (#24)

	if w.UserID == "" {
		return fmt.Errorf("user_id is required")
	}

	// Default user_type if not set
	if w.UserType == "" {
		w.UserType = "user"
	}

	// Default FDID if not set
	if w.FDID == 0 {
		w.FDID = 1
	}

	if w.CurrentProjectID != "" {
		projectUserID, err := s.repo.GetProjectUserID(ctx, w.CurrentProjectID)
		if err != nil {
			return fmt.Errorf("invalid project ID: %w", err)
		}
		if projectUserID != w.UserID {
			return fmt.Errorf("user mismatch: project belongs to %s, worker belongs to %s", projectUserID, w.UserID)
		}
	}

	// If worker has auth data, mark as pending registration
	hasAuthData := w.FaceImgLoc != "" || w.CardNumber != ""
	if hasAuthData {
		w.IsSynced = domain.SyncStatusPendingRegistration
	}

	err := s.repo.Create(ctx, w)
	if err == nil {
		s.analyticsService.LogActivity(ctx, w.UserID, "Worker Created", "worker", w.ID, fmt.Sprintf("Worker %s (%s) created", w.Name, w.PersonIDNo))
	}
	return err
}

func (s *WorkerService) validateWorker(w *domain.Worker) error {
	if w.PersonIDNo != "" && !validation.ValidateNRICFIN(w.PersonIDNo) {
		return apperrors.NewValidationError("invalid person_id_no format (NRIC/FIN)")
	}
	if w.PersonIDAndWorkPassType != "" && !validation.ValidateWorkPassType(w.PersonIDAndWorkPassType) {
		return apperrors.NewValidationError("invalid person_id_and_work_pass_type (Enum: SP, SB, EP, SPASS, WP, ENTREPASS, LTVP)")
	}
	if w.PersonNationality != "" && len(w.PersonNationality) != 2 {
		return apperrors.NewValidationError("person_nationality must be 2 characters (ISO 3166)")
	}
	if w.PersonTrade != "" && !validation.ValidatePersonTrade(w.PersonTrade) {
		return apperrors.NewValidationError("invalid person_trade (e.g. 1.1, 2.5, etc.)")
	}
	return nil
}

func (s *WorkerService) applyPayloadToWorker(existing *domain.Worker, req *domain.UpdateWorkerRequest) {
	if req.Name != nil {
		existing.Name = *req.Name
	}
	if req.UserType != nil {
		existing.UserType = *req.UserType
	}
	if req.Status != nil {
		existing.Status = *req.Status
	}
	if req.PersonIDNo != nil {
		existing.PersonIDNo = *req.PersonIDNo
	}
	if req.PersonIDAndWorkPassType != nil {
		existing.PersonIDAndWorkPassType = *req.PersonIDAndWorkPassType
	}
	if req.PersonNationality != nil {
		existing.PersonNationality = *req.PersonNationality
	}
	if req.PersonTrade != nil {
		existing.PersonTrade = *req.PersonTrade
	}
}

func (s *WorkerService) UpdateWorker(ctx context.Context, userID, id string, req *domain.UpdateWorkerRequest) error {
	if userID == "" {
		return apperrors.NewPermissionDenied("user_id scope required")
	}

	existing, err := s.repo.Get(ctx, userID, id)
	if err != nil {
		return err
	}

	// Dynamic overlay logic
	// Temporarily apply modifications for validation
	temp := *existing
	s.applyPayloadToWorker(&temp, req)
	if err := s.validateWorker(&temp); err != nil {
		return err
	}

	requiresSync := false
	wasRegistered := existing.FaceImgLoc != "" || existing.CardNumber != ""

	// Dynamic overlay logic
	if req.Name != nil {
		if existing.Name != *req.Name {
			requiresSync = true
		}
		existing.Name = *req.Name
	}
	if req.UserType != nil {
		existing.UserType = *req.UserType
	}
	if req.Status != nil {
		existing.Status = *req.Status
		if *req.Status == "inactive" {
			existing.CurrentProjectID = ""
		}
	}
	if req.PersonIDNo != nil {
		existing.PersonIDNo = *req.PersonIDNo
	}
	if req.UserID != nil {
		existing.UserID = *req.UserID
	}
	if req.PersonIDAndWorkPassType != nil {
		existing.PersonIDAndWorkPassType = *req.PersonIDAndWorkPassType
	}
	if req.PersonNationality != nil {
		existing.PersonNationality = *req.PersonNationality
	}
	if req.PersonTrade != nil {
		existing.PersonTrade = *req.PersonTrade
	}

	if req.AuthStartTime != nil {
		if timeutil.CleanDateTime(existing.AuthStartTime) != timeutil.CleanDateTime(*req.AuthStartTime) {
			requiresSync = true
		}
		existing.AuthStartTime = *req.AuthStartTime
	}
	if req.AuthEndTime != nil {
		if timeutil.CleanDateTime(existing.AuthEndTime) != timeutil.CleanDateTime(*req.AuthEndTime) {
			requiresSync = true
		}
		existing.AuthEndTime = *req.AuthEndTime
	}
	if req.FaceImgLoc != nil {
		if existing.FaceImgLoc != *req.FaceImgLoc {
			requiresSync = true
		}
		existing.FaceImgLoc = *req.FaceImgLoc
	}
	if req.CardNumber != nil {
		if existing.CardNumber != *req.CardNumber {
			requiresSync = true
		}
		existing.CardNumber = *req.CardNumber
	}
	if req.CardType != nil {
		if existing.CardType != *req.CardType {
			requiresSync = true
		}
		existing.CardType = *req.CardType
	}
	if req.FDID != nil {
		if existing.FDID != *req.FDID {
			requiresSync = true
		}
		existing.FDID = *req.FDID
	}

	isRegistered := existing.FaceImgLoc != "" || existing.CardNumber != ""

	// Project ID flexibility
	var newProjectID string
	if req.CurrentProjectID != nil {
		newProjectID = *req.CurrentProjectID
	} else if req.ProjectID != nil {
		newProjectID = *req.ProjectID
	} else {
		newProjectID = existing.CurrentProjectID
	}

	if newProjectID != existing.CurrentProjectID {
		if newProjectID != "" {
			projectUserID, err := s.repo.GetProjectUserID(ctx, newProjectID)
			if err != nil {
				return fmt.Errorf("invalid project ID: %w", err)
			}
			if projectUserID != existing.UserID {
				return fmt.Errorf("security violation: cannot assign project from different user")
			}
		}
		existing.CurrentProjectID = newProjectID
		requiresSync = true
	} else if req.CurrentProjectID != nil && *req.CurrentProjectID == "" {
		if existing.CurrentProjectID != "" {
			requiresSync = true
		}
		existing.CurrentProjectID = ""
	}

	if requiresSync && (wasRegistered || isRegistered) {
		// Only set to pending update if it was previously synced or already pending update
		if existing.IsSynced != domain.SyncStatusPendingRegistration {
			existing.IsSynced = domain.SyncStatusPendingUpdate
		}
	} else {
		if req.IsSynced != nil {
			existing.IsSynced = *req.IsSynced
		}
	}

	if err := s.repo.Update(ctx, existing); err != nil {
		return err
	}

	s.analyticsService.LogActivity(ctx, userID, "Worker Updated", "worker", id, fmt.Sprintf("Worker %s updated", existing.Name))
	return nil
}

func (s *WorkerService) DeleteWorker(ctx context.Context, userID, id string) error {
	if userID == "" {
		return apperrors.NewPermissionDenied("user_id scope required")
	}
	err := s.repo.Delete(ctx, userID, id)
	if err == nil {
		s.analyticsService.LogActivity(ctx, userID, "Worker Deleted", "worker", id, "Worker permanently removed from system")
	}
	return err
}

func (s *WorkerService) ListPendingSyncWorkers(ctx context.Context, userID string) ([]domain.Worker, error) {
	// Fetch workers needing registration and update
	registerWorkers, err := s.repo.ListByIsSynced(ctx, userID, domain.SyncStatusPendingRegistration)
	if err != nil {
		return nil, fmt.Errorf("failed to list register-pending workers: %w", err)
	}

	updateWorkers, err := s.repo.ListByIsSynced(ctx, userID, domain.SyncStatusPendingUpdate)
	if err != nil {
		return nil, fmt.Errorf("failed to list update-pending workers: %w", err)
	}

	return append(registerWorkers, updateWorkers...), nil
}

func (s *WorkerService) AssignWorkersToProject(ctx context.Context, projectID string, workerIDs []string) error {
	userID, err := s.repo.GetProjectUserID(ctx, projectID)
	if err != nil {
		return fmt.Errorf("failed to verify project: %w", err)
	}

	err = s.repo.AssignToProject(ctx, projectID, workerIDs, userID)
	if err == nil {
		actorUserID := ports.GetUserID(ctx)
		s.analyticsService.LogActivity(ctx, actorUserID, "Worker Assigned", "project", projectID, fmt.Sprintf("Bulk assignment of %d workers to project %s", len(workerIDs), projectID))
	}
	return err
}
